apiVersion: v1
kind: Secret
metadata:
  name: storageos-secret
type: "kubernetes.io/storageos"
data:
  apiAddress: dGNwOi8vMzUuMTk3LjE5My45MDo1NzA1
  apiUsername: c3RvcmFnZW9z
  apiPassword: c3RvcmFnZW9z