---
apiVersion: v1
kind: Service
metadata:
  name: storageos-api
spec:
  ports:
  - port: 5705
    targetPort: 5705
    name: http
  type: LoadBalancer
  selector:
    name: storageos
  externalIPs:
  - 80.11.12.10

---
apiVersion: v1
kind: Endpoints
apiVersion: v1
metadata:
  name: storageos-api
subsets:
  - addresses:
      - ip: [[HOST2_IP]]
    ports:
      - port: 5705
        name: http
