apiVersion: v1
kind: Secret
metadata:
  name: storageos-secret
type: "kubernetes.io/storageos"
data:
  apiAddress: dGNwOi8vMTcyLjE3LjAuODE6NTcwNQ==
  apiUsername: c3RvcmFnZW9z
  apiPassword: c3RvcmFnZW9z
