apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlpvc
  labels:
    storageos.com/replicas: "1"
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
