apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redispvc
  annotations:
    volume.beta.kubernetes.io/storage-class: fast001
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
